# -*- coding: utf-8 -*-
"""image recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143zz1Fm1RoO25JtNgT27Ujg3jbbYf5-t
"""

!git clone https://github.com/ultralytics/yolov5
!pip install -r requirements.txt

!nvidia-smi

!python detect.py --weights yolov5s.pt --source data/images --conf 0.25

!python segment/train.py --data coco128-seg.yaml --weights yolov5s-seg.pt --epochs 50

from google.colab import files
import os

uploaded = files.upload()  # Upload video manually

# Fix the filename if it contains spaces or brackets
video_path = list(uploaded.keys())[0]
new_video_path = "video.mp4"
os.rename(video_path, new_video_path)

print(f"Uploaded file renamed to: {new_video_path}")

!python segment/predict.py --weights runs/train-seg/exp/weights/best.pt --source "video.mp4" --save-txt --save-conf --save-crop

!ls runs/predict-seg/

!ls runs/predict-seg/exp15/

from google.colab import files
files.download("runs/predict-seg/exp15/video.mp4")  # Correct path dalna

